# Generated by Django 5.2.15 on 2026-07-02 10:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='song',
            unique_together={('title', 'artist', 'uploaded_by')},
        ),
    ]
